//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS2015Form
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormReply
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string School { get; set; }
        public string Department { get; set; }
        public string Grade { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int Q1 { get; set; }
        public int Q2 { get; set; }
        public int Q3 { get; set; }
        public bool Q4_AA { get; set; }
        public bool Q4_MAA { get; set; }
        public bool Q4_SAA { get; set; }
        public bool Q4_RDAA { get; set; }
        public string Q5 { get; set; }
        public string Q6 { get; set; }
        public bool REG { get; set; }
    }
}
